project:
  type: website
  output-dir: docs

website:
  title: "Vinay Varma"
  navbar:
    right:
      - posts.qmd
      - href: home.qmd
        text: Home
    left: 
      - text: "Neural Networks: Zero to Hero"
        href: https://neuralnetszerotohero.github.io/

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



