project:
  type: website
  output-dir: docs

website:
  title: "Vinay Varma"
  navbar:
    right:
      - href: home.qmd
        text: Home
      - posts.qmd
    

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

resources:
  - CNAME



